services:
  valkey:
    image: "valkey/valkey"
    container_name: valkey
    ports:
      - "6379:6379"
  minio:
    image: "quay.io/minio/minio"
    container_name: minio
    ports:
      - "9000:9000"
      - "9001:9001"
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: root
      MINIO_ROOT_PASSWORD: changeme
    volumes:
      - ${HOME}/minio/data:/data
