name: Manual Build & Push

on:
  workflow_dispatch:

jobs:
  Build-and-Push:
    runs-on: ubuntu-24.04
    steps:
        - name: Checkout code
          uses: actions/checkout@v4

        - name: Log in to Docker Hub
          run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

        - name: Build Docker image
          run: docker build -t "${{ secrets.DOCKERHUB_USERNAME }}/hivebox:latest" .
