name: Manual Build & Push

on:
  workflow_dispatch:

jobs:
  Build-and-Push:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout branch
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}

      - name: Fetch all tags
        run: git fetch --tags

      - name: Get latest tag
        id: get_tag
        run: |
          TAG=$(git describe --tags --abbrev=0)
          echo "TAG=$TAG"
          echo "IMAGE_TAG=$TAG" >> $GITHUB_ENV

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      - name: Build Docker image
        run: docker build -t "${{ secrets.DOCKERHUB_USERNAME }}/hivebox:${{ env.IMAGE_TAG }}" .

      - name: Push Docker image
        run: docker push "${{ secrets.DOCKERHUB_USERNAME }}/hivebox:${{ env.IMAGE_TAG }}"
